language: csharp
solution: ./src/EATeX.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore ./src/EATeX.sln

script:
  - xbuild ./src/EATeX.sln
  - nunit-console ./src/EATeX.Test/bin/Debug/EATeX.Test.dll